---
stages:
  - 'Build'
  - 'Trigger'

'Preprocess templates':
  stage: 'Build'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - 'git config --global user.name "Dotfiles CI"'
    - 'git config --global user.email james@james.tl'
    - 'eval $(ssh-agent -s)'
    - 'chmod 600 "$SSH_PRIVATE_KEY" && ssh-add "$SSH_PRIVATE_KEY"'
    - 'git remote set-url origin git@gitlab.james.tl:james/dotfiles.git'
  script:
    - './.refresh'
    - 'git add -f .'
    - 'git commit -m "Preprocess templates" --no-gpg-sign'
    - 'git push --force origin HEAD:preprocessed'

.'Refresh stage1':
  stage: 'Trigger'
  variables:
    BUILD: 'server'
    REFRESH: 'true'
  trigger:
    project: 'nest/stage1'
